#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Parallel-ForkManager
Version  : 2.02
Release  : 20
URL      : https://cpan.metacpan.org/authors/id/Y/YA/YANICK/Parallel-ForkManager-2.02.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/Y/YA/YANICK/Parallel-ForkManager-2.02.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libp/libparallel-forkmanager-perl/libparallel-forkmanager-perl_1.19-1.debian.tar.xz
Summary  : 'A simple parallel processing fork manager'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-Parallel-ForkManager-license = %{version}-%{release}
Requires: perl-Parallel-ForkManager-perl = %{version}-%{release}
BuildRequires : buildreq-cpan
BuildRequires : perl(Devel::GlobalDestruction)
BuildRequires : perl(Module::Runtime)
BuildRequires : perl(Moo)
BuildRequires : perl(Moo::Role)
BuildRequires : perl(Role::Tiny)
BuildRequires : perl(Sub::Exporter::Progressive)
BuildRequires : perl(Sub::Quote)
BuildRequires : perl(Sub::Uplevel)
BuildRequires : perl(Test::Warn)

%description
# NAME
Parallel::ForkManager - A simple parallel processing fork manager
# VERSION

%package dev
Summary: dev components for the perl-Parallel-ForkManager package.
Group: Development
Provides: perl-Parallel-ForkManager-devel = %{version}-%{release}
Requires: perl-Parallel-ForkManager = %{version}-%{release}

%description dev
dev components for the perl-Parallel-ForkManager package.


%package license
Summary: license components for the perl-Parallel-ForkManager package.
Group: Default

%description license
license components for the perl-Parallel-ForkManager package.


%package perl
Summary: perl components for the perl-Parallel-ForkManager package.
Group: Default
Requires: perl-Parallel-ForkManager = %{version}-%{release}

%description perl
perl components for the perl-Parallel-ForkManager package.


%prep
%setup -q -n Parallel-ForkManager-2.02
cd %{_builddir}
tar xf %{_sourcedir}/libparallel-forkmanager-perl_1.19-1.debian.tar.xz
cd %{_builddir}/Parallel-ForkManager-2.02
mkdir -p deblicense/
cp -r %{_builddir}/debian/* %{_builddir}/Parallel-ForkManager-2.02/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Parallel-ForkManager
cp %{_builddir}/debian/copyright %{buildroot}/usr/share/package-licenses/perl-Parallel-ForkManager/4127ca28982b99d5686b246efe7cbe07cf8f0267
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Parallel::ForkManager.3
/usr/share/man/man3/Parallel::ForkManager::Child.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-Parallel-ForkManager/4127ca28982b99d5686b246efe7cbe07cf8f0267

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
